AllCops:
  SuggestExtensions: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false
  
Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/DuplicateMethods:
  Exclude:
    - 'lib/awspec/type/codedeploy_deployment_group.rb'
    - 'lib/awspec/type/ecs_container_instance.rb'
    - 'lib/awspec/type/ecs_service.rb'
    - 'lib/awspec/type/eks_nodegroup.rb'
    - 'lib/awspec/type/resource_base.rb'

Lint/ErbNewArguments:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'lib/awspec/generator/doc/type/account_attribute.rb'
    - 'lib/awspec/generator/doc/type/account_attribute_base.rb'
    - 'lib/awspec/type/account_attribute.rb'
    - 'lib/awspec/type/resource_base.rb'

Lint/SuppressedException:
  Exclude:
    - 'Rakefile'

Lint/UnreachableLoop:
  Exclude:
    - 'lib/awspec/type/nat_gateway.rb'
    - 'lib/awspec/type/route53_hosted_zone.rb'

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Max: 60

Metrics/BlockLength:
  Max: 60

Metrics/ClassLength:
  Max: 130

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  MaxOptionalParameters: 4

Metrics/PerceivedComplexity:
  Max: 30

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  Exclude:
    - 'lib/awspec/generator/spec/security_group.rb'
    - 'lib/awspec/helper/client_wrap.rb'
    - 'lib/awspec/type/network_acl.rb'

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Security/Eval:
  Exclude:
    - 'lib/awspec/command/generate.rb'
    - 'lib/awspec/generator/doc/type.rb'
    - 'lib/awspec/helper/type.rb'
    - 'lib/awspec/type/account.rb'
    - 'lib/awspec/type/account_attribute.rb'
    - 'spec/generator/doc/type_spec.rb'

Style/CaseLikeIf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'lib/awspec/helper.rb'

Style/MutableConstant:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: AllowMethodsWithArguments, IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Exclude:
    - 'lib/awspec/generator/spec/route53_hosted_zone.rb'
    - 'lib/awspec/helper/finder/iam.rb'
    - 'lib/awspec/helper/finder/lambda.rb'
    - 'lib/awspec/helper/finder/vpc.rb'
    - 'lib/awspec/type/ec2.rb'
    - 'lib/awspec/type/eks_nodegroup.rb'
    - 'lib/awspec/type/firehose.rb'
    - 'lib/awspec/type/route53_hosted_zone.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInArrayLiteral:
  Exclude:
    - 'lib/awspec/generator/doc/type/alb.rb'

# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 4

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: forbid_for_all_comparison_operators, forbid_for_equality_operators_only, require_for_all_comparison_operators, require_for_equality_operators_only
Style/YodaCondition:
  Exclude:
    - 'lib/awspec/generator/doc/type/base.rb'
